name: spot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.2.0'

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage

      # - name: Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      #   with:
      #     min_coverage: 95
